// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
#include <map_export.h>  // Generated by Cmake
#include <Building.h>
size_t Building::kBuildingSize = 0;
MAP_EXPORT BuildingPtr Building::Create() {return BuildingPtr(new Building());}
MAP_EXPORT size_t Building::BuildingSize() {return kBuildingSize;}
MAP_NO_EXPORT Building::Building() {index_ = kBuildingSize++;}
