// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
#ifndef UNNAMING_GAME_SRC_GRAPHIC_RENDERER_CMAKE_H_
#define UNNAMING_GAME_SRC_GRAPHIC_RENDERER_CMAKE_H_
#ifdef USING_LIBRARIES_CMAKE
#include <renderer_export.h>  // Generated by Cmake
#else
#define RENDERER_EXPORT
#define RENDERER_NO_EXPORT
#endif
#endif  // UNNAMING_GAME_SRC_GRAPHIC_RENDERER_CMAKE_H_
