@startuml
hide members
namespace visible {
  interface Block
  Block <|.. BaseBlock
}
namespace hidden {
  interface Block::Implementation
  Block::Implementation <|-- BaseBlock::Implementation
}
namespace component {
  Block o-- Block::Implementation
  BaseBlock *-- BaseBlock::Implementation
  Block ..> Block::Implementation
  BaseBlock ..> BaseBlock::Implementation
}
@enduml
