@startuml
hide members
namespace visible {
  interface Building
  Building <|.. BaseBuilding
  Building <|.. LinkBuilding
}
namespace hidden {
  interface Building::Implementation
  Building::Implementation <|-- BaseBuilding::Implementation
  Building::Implementation <|-- LinkBuilding::Implementation
}
namespace component {
  Building o-- Building::Implementation
  BaseBuilding *-- BaseBuilding::Implementation
  LinkBuilding *-- LinkBuilding::Implementation
  Building ..> Building::Implementation
  BaseBuilding ..> BaseBuilding::Implementation
  LinkBuilding ..> LinkBuilding::Implementation
}
@enduml
